# Generated by Django 3.0.5 on 2020-04-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20200425_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Section'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(default='test teacher', max_length=200, null=True),
        ),
    ]
