# Generated by Django 3.0.5 on 2020-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_auto_20200428_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_code',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(default='this id your lecture, document type lecture'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
