# Generated by Django 3.0.5 on 2020-04-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20200429_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(default='this id your lecture, document type lecture')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Tutor')),
            ],
        ),
    ]
