# Generated by Django 3.0.5 on 2020-04-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200425_2309'),
        ('teacher', '0016_assignment_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_ques',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.Stud'),
        ),
        migrations.CreateModel(
            name='Assignment_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(default='this id your lecture, document type lecture')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Stud')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Tutor')),
            ],
        ),
    ]
