# Generated by Django 3.0.5 on 2020-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='name',
            field=models.CharField(default='test student', max_length=200, null=True),
        ),
    ]
