# Generated by Django 3.0.5 on 2020-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200425_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='email',
            field=models.CharField(default='name@mail', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='phone',
            field=models.CharField(default='1234', max_length=200, null=True),
        ),
    ]
